src/main/java/demo/form/ChangePasswordForm.java
package demo.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.validator.ValidatorForm;

public class ChangePasswordForm extends ValidatorForm {
	private static final long serialVersionUID = 1L;
	
	private String password, passwordAgain;
	
	
	

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordAgain() {
		return passwordAgain;
	}

	public void setPasswordAgain(String passwordAgain) {
		this.passwordAgain = passwordAgain;
	}

	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		super.reset(mapping, request);
		this.password = null;
		this.passwordAgain = null;
	}

	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		if (this.password == null || this.passwordAgain == null || this.password.trim().length() == 0 || !this.password.equals(this.passwordAgain)) {
			ActionErrors errors = new ActionErrors();
			errors.add("password", new ActionMessage("password.change.mismatch"));
			return errors;
		}
		return super.validate(mapping, request);
	}
	
	
	
}

src/main/java/demo/pojo/Run.java
package demo.pojo;

import java.io.Serializable;

public class Run implements Serializable {
	private static final long serialVersionUID = 1L;

	private Runner runner;
	private Integer finishingSeconds;
	
	
	public Runner getRunner() {
		return runner;
	}
	public void setRunner(Runner runner) {
		this.runner = runner;
	}
	
	
	public Integer getFinishingSeconds() {
		return finishingSeconds;
	}
	public void setFinishingSeconds(Integer finishingSeconds) {
		this.finishingSeconds = finishingSeconds;
	}
	
	
	public Integer getFinishingPixels() {
		return finishingSeconds / 80;
	}

	public String getFinishingTime() {
		if (finishingSeconds == null || finishingSeconds == 0) return null;
		StringBuilder timeString = new StringBuilder();
		int hours = finishingSeconds / 3600;
		int rest =  finishingSeconds - hours*3600;
		int minutes = rest / 60;
		int seconds = rest - minutes*60;
		timeString.append(hours).append(':');
		if (minutes < 10) timeString.append('0');
		timeString.append(minutes).append(':');
		if (seconds < 10) timeString.append('0');
		timeString.append(seconds);
		return timeString.toString();
	}
	
	
	@Override
	public String toString() {
		return "RunBean [runner=" + runner + ", finishingSeconds="
				+ finishingSeconds + "]";
	}
	
	
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((finishingSeconds == null) ? 0 : finishingSeconds.hashCode());
		result = prime * result + ((runner == null) ? 0 : runner.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Run other = (Run) obj;
		if (finishingSeconds == null) {
			if (other.finishingSeconds != null)
				return false;
		} else if (!finishingSeconds.equals(other.finishingSeconds))
			return false;
		if (runner == null) {
			if (other.runner != null)
				return false;
		} else if (!runner.equals(other.runner))
			return false;
		return true;
	}
	
	
	
}

src/main/java/demo/action/ChangePasswordAction.java
package demo.action;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;

import javax.naming.NamingException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import demo.dao.DAOUtils;
import demo.dao.SystemDAO;
import demo.form.ChangePasswordForm;
import demo.util.SessionListener;

public class ChangePasswordAction extends Action {

	public static final String FORWARD_changePassword = "changePassword";


	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException, SQLException, ServletException, NamingException {
		ChangePasswordForm changePasswordForm = (ChangePasswordForm) form;
		if (request.getMethod().equalsIgnoreCase("POST") 
				&& changePasswordForm.getPassword() != null
				&& changePasswordForm.getPassword().length() > 0
				&& changePasswordForm.getPassword().equals(changePasswordForm.getPasswordAgain())) {
			// check token for the very sensitive delete-all functionality
			final String expectedSecret = (String) request.getSession().getAttribute(SessionListener.SENSITIVE_ACTIONS_TOKEN);
			if (!expectedSecret.equals(request.getParameter("secret"))) {
				throw new ServletException("Missing or wrong secret");
			}

			Connection connection = null;
			try {
				connection = DAOUtils.getConnection();
				SystemDAO systemDAO = new SystemDAO(connection);
				systemDAO.changePassword(request.getUserPrincipal().getName(), changePasswordForm.getPassword());
				request.setAttribute("UpdateResultMessage", "Password has been changed.");
			} finally {
				if (connection != null) connection.close();
			}

			changePasswordForm.setPassword(null);
			changePasswordForm.setPasswordAgain(null);
		}
		return mapping.findForward(FORWARD_changePassword);
	}
	
}

src/main/java/demo/action/EditResultsViaImportAction.java
package demo.action;

import java.sql.SQLException;

import javax.naming.NamingException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public class EditResultsViaImportAction extends Action {

	public static final String FORWARD_editResultsViaImport = "editResultsViaImport";
	
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException, NamingException {

		return mapping.findForward(FORWARD_editResultsViaImport);
	}

	
	
}

src/main/java/demo/action/EditRunnerPhotoAction.java
package demo.action;

import java.sql.SQLException;

import javax.naming.NamingException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public class EditRunnerPhotoAction extends Action {

	public static final String FORWARD_editRunnerPhoto = "editRunnerPhoto";
	
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException, NamingException {

		return mapping.findForward(FORWARD_editRunnerPhoto);
	}

	
	
}

src/main/java/demo/action/ShowMarathonsAction.java
package demo.action;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import javax.naming.NamingException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import demo.dao.DAOUtils;
import demo.dao.MarathonDAO;
import demo.pojo.Marathon;

public class ShowMarathonsAction extends Action {

	public static final String FORWARD_showMarathons = "showMarathons";
	
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException, NamingException {
		
		// TODO think of using caching to avoid hitting the database too often

		final List<Marathon> marathons;
		
		Connection connection = null;
		try {
			connection = DAOUtils.getConnection();
			MarathonDAO marathonDAO = new MarathonDAO(connection);
			marathons = marathonDAO.loadMarathons();
		} finally {
			if (connection != null) connection.close();
		}
		
		request.setAttribute("marathons", marathons);
		return mapping.findForward(FORWARD_showMarathons);
	}

	
	
}

src/main/java/demo/action/ShowResultsAction.java
package demo.action;

import java.sql.Connection;
import java.sql.SQLException;

import javax.naming.NamingException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import demo.dao.DAOUtils;
import demo.dao.ResultsDAO;
import demo.pojo.Results;

public class ShowResultsAction extends Action {

	public static final String FORWARD_showResults = "showResults";
	public static final String FORWARD_showChart = "showChart";

	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException, NamingException {
		
		Results results, resultsFinished;
		final boolean svg = "svg".equals(request.getParameter("type"));
		final boolean includePending = request.isUserInRole("administrator") && !svg;
		
		Connection connection = null;
		try {
			connection = DAOUtils.getConnection();
			ResultsDAO resultsDAO = new ResultsDAO(connection);
			String marathon = (String)request.getAttribute("marathon");
			if (marathon == null) {
				marathon = request.getParameter("marathon");
			}
			results = resultsDAO.loadResults( marathon, includePending );
			resultsFinished = resultsDAO.loadResults( marathon, false );
		} finally {
			if (connection != null) connection.close();
		}
		
		request.setAttribute("results", results);
		request.setAttribute("resultsFinished", resultsFinished);
		return svg ? mapping.findForward(FORWARD_showChart) : mapping.findForward(FORWARD_showResults);
	}

	
	
}

src/main/java/demo/action/ShowRunnerAction.java
package demo.action;

import java.sql.Connection;
import java.sql.SQLException;

import javax.naming.NamingException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import demo.dao.DAOUtils;
import demo.dao.RunnerDAO;
import demo.pojo.Runner;

public class ShowRunnerAction extends Action {

	public static final String FORWARD_showRunner = "showRunner";
	public static final String FORWARD_showError = "showError";
	
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException, NamingException {

		final String runnerId = request.getParameter("runner");
		
		final Runner runner;
		
		Connection connection = null;
		try {
			connection = DAOUtils.getConnection();
			RunnerDAO runnerDAO = new RunnerDAO(connection);
			if (runnerDAO.hasRunnerFinished(runnerId)) {
				// TODO: Style the runner's profile with a star "has finished"
				System.out.println("Accessing a runner's profile who has finished");
			}
			runner = runnerDAO.loadRunner(Long.parseLong(runnerId));
		} catch (Exception e) {
			e.printStackTrace();
			return mapping.findForward(FORWARD_showError);
		} finally {
			if (connection != null) connection.close();
		}
		
		request.setAttribute("runner", runner);
		return mapping.findForward(FORWARD_showRunner);
	}

	
	
}

src/main/java/demo/action/ShowRunnerAttendancesAction.java
package demo.action;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import javax.naming.NamingException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import demo.dao.AttendanceDAO;
import demo.dao.DAOUtils;
import demo.dao.RunnerDAO;
import demo.form.RunnerAttendancesForm;
import demo.pojo.Attendance;
import demo.pojo.Runner;

public class ShowRunnerAttendancesAction extends Action {

	public static final String FORWARD_showRunnerAttendances = "showRunnerAttendances";
	
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException, NamingException {

		final String runnerUsername = request.getUserPrincipal().getName();
		
		final Runner runner;
		final List<Attendance> attendances;
		
		Connection connection = null;
		try {
			connection = DAOUtils.getConnection();
			
			RunnerDAO runnerDAO = new RunnerDAO(connection);
			AttendanceDAO attendanceDAO = new AttendanceDAO(connection);

			runner = runnerDAO.loadRunnerByName(runnerUsername);
			attendances = attendanceDAO.loadAttendingMarathons(runner);
			
			RunnerAttendancesForm runnerAttendancesForm = (RunnerAttendancesForm)form;
			runnerAttendancesForm.setAttendances(attendances);
		} finally {
			if (connection != null) connection.close();
		}
		
		request.setAttribute("runner", runner);
		request.setAttribute("attendancesList", attendances);
		return mapping.findForward(FORWARD_showRunnerAttendances);
	}

	
	
}

src/main/java/demo/action/ShowRunnerProfileAction.java
package demo.action;

import java.sql.Connection;
import java.sql.SQLException;

import javax.naming.NamingException;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import demo.dao.DAOUtils;
import demo.dao.RunnerDAO;
import demo.form.RunnerForm;
import demo.pojo.Runner;

public class ShowRunnerProfileAction extends Action {

	public static final String FORWARD_showRunnerProfile = "showRunnerProfile";
	public static final String FORWARD_showAdminWelcome = "showAdminWelcome";
	
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException, NamingException {

		String runnerUsername = null;
		Long runnerId = null;
		
		// admin may visit all profiles, normal runner only his/her
		if (request.isUserInRole("administrator")) {
			String runnerIdParam = request.getParameter("runnerId");
			if (runnerIdParam == null) {
				return mapping.findForward(FORWARD_showAdminWelcome);
			}
			runnerId = Long.parseLong(runnerIdParam);
		} else if (request.isUserInRole("runner")) {
			runnerUsername = request.getUserPrincipal().getName();
		} else {
			throw new IllegalArgumentException("Unauthorized to view runner given as param");
		}
		
		
		final Runner runner;
		
		Connection connection = null;
		try {
			connection = DAOUtils.getConnection();
			RunnerDAO runnerDAO = new RunnerDAO(connection);
			if (runnerUsername != null) {
				runner = runnerDAO.loadRunnerByName(runnerUsername);
			} else {
				runner = runnerDAO.loadRunner(runnerId);
			}
			RunnerForm runnerForm = (RunnerForm)form;
			runnerForm.setRunner(runner);
		} finally {
			if (connection != null) connection.close();
		}
		
		
		// remember user prefill of form
		if (runnerUsername != null) {
			Cookie userNameRememberer = new Cookie("marathonUserLoginBoxDefault", runnerUsername);
			userNameRememberer.setMaxAge(60*60*24*30);
			response.addCookie(userNameRememberer);
		}
		
		request.setAttribute("runner", runner);
		return mapping.findForward(FORWARD_showRunnerProfile);
	}

	
	
}

src/main/webapp/WEB-INF/pages/changePassword.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %> 
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %> 
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %> 
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %> 
<!DOCTYPE html>
<html>
<head>
    <%@include file="/WEB-INF/parts/header.jsp" %>
	<link href="/marathon/css/style.css" rel="stylesheet" type="text/css"/>
	<title>Marathon</title>
</head>
<%--<body class="metro"> --%>
<body>




    <h2>Here you can change your password</h2>


    
    <html:form action="/secured/updatePassword" method="POST">
    	<input type="hidden" name="secret" value="${sessionScope['SENSITIVE_ACTIONS_TOKEN']}" />
	    <table>
	        <tr>
	            <td>Password:</td>
                <td><input type="password" name="password" size="30" maxlength="50" autocomplete="off" /></td>
	        </tr>
	        <tr>
	            <td>Retype password again:</td>
                <td><input type="password" name="passwordAgain" size="30" maxlength="50" autocomplete="off" /></td>
	        </tr>
	        <tr>
	           <td></td>
	           <td align="right"><html:submit>&nbsp;&nbsp;&nbsp;&nbsp;Change password&nbsp;&nbsp;&nbsp;&nbsp;</html:submit></td>
	        </tr>
	        <tr>
	        	<td colspan="2"><b>${requestScope.UpdateResultMessage}</b></td>
	        </tr>
	    </table>


	    <b><html:errors /></b>
    </html:form>

    <%@include file="/WEB-INF/parts/footer.jsp" %>
</body>
</html>

src/main/webapp/WEB-INF/pages/dynamicRunnerDetails.jsp
<%@ page language="java" contentType="application/json" pageEncoding="ISO-8859-1"%>
runner = {
	"firstname": "${runner.firstname}",
	"lastname": "${runner.lastname}",
	"street": "${runner.street}",
	"zip": "${runner.zip}",
	"city": "${runner.city}",
	"cc": "${runner.creditCardNumber}"
}

src/main/webapp/WEB-INF/pages/editResultsViaImport.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %> 
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %> 
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %> 
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %> 
<!DOCTYPE html>
<html>
<head>
    <%@include file="/WEB-INF/parts/header.jsp" %>
	<title>Marathon</title>
</head>
<body class="metro">

    <%@include file="/WEB-INF/parts/navigation.jsp" %>


    <h2>Mass update of results via import</h2>
	
	     
    <b><html:errors /></b>
    
     
	<div class="panel">
	    <div class="panel-header">
	        Upload import XML (plain XML or zipped) of result data:
	    </div>
	    <div class="panel-content">
						    		
		
		    <html:form action="/admin/updateResultsViaImport" method="POST" enctype="multipart/form-data">
			    <html:hidden property="marathon" value="${fn:escapeXml(param.marathon)}"/>
			    
		        <html:file property="xmlResultsFile"/> 
		
		        <html:submit>Upload</html:submit>
		    </html:form>
		    
	    </div>
	</div>    


    <%@include file="/WEB-INF/parts/footer.jsp" %>
</body>
</html>

src/main/webapp/WEB-INF/pages/loginfail.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
    <%@include file="/WEB-INF/parts/header.jsp" %>
	<link href="/marathon/css/style.css" rel="stylesheet" type="text/css"/>
	<title>Login</title>
</head>
<body class="metro">
    
    Wrong username or password!
    <p/>
    Use your browser's back button to try again...
    
</body>
</html>

src/main/webapp/WEB-INF/pages/showResultChart.jsp
<%@ page language="java" contentType="image/svg+xml; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %> 
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %> 
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %> 
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %> 
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="encode" uri="https://www.owasp.org/index.php/OWASP_Java_Encoder_Project" %>


<svg xmlns="http://www.w3.org/2000/svg" version="1.1" 
	 class="chart" width="200" height="120">
	<script> <%--  type="text/ecmascript" --%>
	  var names = new Array();
	  <logic:iterate id="result" indexId="position" length="3" name="results" property="runs">
	  	names[${position}] = "${fn:escapeXml(result.runner.firstname)} ${fn:escapeXml(result.runner.lastname)}";
	  </logic:iterate>
	  
	  function showName(evt, idx) {
	     evt.target.setAttributeNS(null,"style","fill:blue");
         titleElement = document.getElementById("chartTitle");
	     titleElement.textContent=names[idx];
	  }	  
	  
	  function hideName(evt) {
	     evt.target.setAttributeNS(null,"style","fill:steelblue");
         titleElement = document.getElementById("chartTitle");
	     titleElement.textContent="";
	  }
	</script>
    <logic:iterate id="result" indexId="position" length="3" name="results" property="runs">
	  <g transform="translate(0,${position*20})">
	    
	    <rect width="${result.finishingPixels}" height="19" style="fill:steelblue;" 
			  onmouseover="showName(evt,${position})" onmouseout="hideName(evt)"></rect>
	    
	    <text x="37" y="9.5" dy=".35em" 
	    	  style="fill:white; font:10px sans-serif; text-anchor:end;">${result.finishingTime}</text>

	  </g>
    </logic:iterate>
    <text id="chartTitle" transform="translate(0,90)" font-family="Helvetica,Arial" font-size="12"></text>
</svg>

src/main/webapp/WEB-INF/pages/showResults.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %> 
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %> 
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %> 
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %> 
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="encode" uri="https://www.owasp.org/index.php/OWASP_Java_Encoder_Project" %>
<!DOCTYPE html>
<html>
<head>
    <%@include file="/WEB-INF/parts/header.jsp" %>
	<title>Marathon Results</title>
</head>
<body class="metro">

    <%@include file="/WEB-INF/parts/navigation.jsp" %>




    <logic:notEmpty name="results" property="marathon">

	    <h2>Marathon Results <bean:write name="results" property="marathon.title" /></h2>
	    <p />


	    <c:choose>
	      <c:when test="${param.refresh != null}">
	        <script>
	          // dynamic refresh interval to allow parameterized refresh rate by caller
	          window.setTimeout('location.reload()', ${fn:escapeXml(param.refresh)});
	        </script>
	      </c:when>
	      <c:otherwise>
	      	Show live results:
	        <a href="/marathon/showResults.page?marathon=${results.marathon.id}&amp;refresh=20000">slow</a>
	         | 
	        <a href="/marathon/showResults.page?marathon=${results.marathon.id}&amp;refresh=5000">quick</a>
	      </c:otherwise>
	    </c:choose>

		<p>&nbsp;</p>
	    
        <logic:present role="administrator">
        	<a href="/marathon/admin/deleteAllResults.page?marathon=${results.marathon.id}&amp;secret=${sessionScope['SENSITIVE_ACTIONS_TOKEN']}">Delete all results</a>
        	<%--
		    <html:link href="/marathon/admin/deleteAllResults.page" paramId="marathon" paramName="results" paramProperty="marathon.id">Delete all results</html:link> --%>
            <p/>
        </logic:present>
	    
	    
	    
	    <table width="98%" border="0">
	    	<tr>
	    		<td valign="top">
			
			
			
			
			
			        <html:form action="/admin/updateResults" method="POST">
			
				        <table border="1" class="profileTable">
				            <tr class="tableHeader">
				                <th>Standings</th>
				                <th>Runner</th>
				                <input type="hidden" 
				                name="marathon" 
				                value="${fn:escapeXml(results.marathon.id)}" />
			                    <th>Time</th>
				            </tr>
				            
				            <logic:iterate id="result" indexId="position" name="results" property="runs">
				            	<% String trClass = position % 2 == 0 ? "white" : "gray"; %>
								<tr class="<%=trClass%>">
				                    <td>
			                            <logic:notPresent role="administrator">
			    	                       ${position + 1}
			   	                        </logic:notPresent>
			                        </td>
				                    <td>
										<c:url var="runnerURL" value="/showRunner.page">
										   <c:param name="runner" value="${result.runner.id}" />
										</c:url>	                       
				                        <a href="${runnerURL}">
				                            ${result.runner.firstname} ${result.runner.lastname}
				                        </a>
				                    </td>
				                    <td>
			                            <logic:present role="administrator">
			                                <input type="text" name="resultsMapped(${result.runner.id})" value="${result.finishingTime}" />
			                            </logic:present>
			                            <logic:notPresent role="administrator">
			                                ${result.finishingTime}
			                            </logic:notPresent>
				                    </td>
				                </tr> 
				            </logic:iterate>
			            
			            </table>
			
			            <logic:present role="administrator">
			                <html:submit>Save</html:submit>
			                <p/>
					        <html:link href="/marathon/admin/editResultsViaImport.page" paramId="marathon" paramName="results" paramProperty="marathon.id">Mass update via import</html:link>
					        <p/>
					        ${requestScope.ImportResultMessage}
			            </logic:present>
			        </html:form>






	    		</td>
	    		
	    		<td valign="top" width="250">
	    		
					<%-- SVG Chart --%>   
					<h3>Top 3 Chart</h3>
					<c:url var="chartURL" value="/showResults.page?marathon=${fn:escapeXml(results.marathon.id)}&type=svg"></c:url>
					<object type="image/svg+xml" data="${chartURL}"></object>
	    			
	    		
	    		</td>
	    	</tr>
	    </table>
	    

    </logic:notEmpty>
    
    <%@include file="/WEB-INF/parts/footer.jsp" %>
</body>
</html>